Bumped version to 2.11.4
Miniboxing is no longer compatible with Scala 2.11.{0,1,2}, since the
compiler releases **are not binary compatible**. There is a but tracking
full cross-compilation, but I just didn't have time to pursue this
further: https://github.com/miniboxing/miniboxing-plugin/issues/140

Just for reference, this is the error you will get:
```
java.lang.NoSuchMethodError: scala.tools.nsc.typechecker.Contexts$class.rootContext$default$4(Lscala/tools/nsc/typechecker/Analyzer;)Z
	at miniboxing.plugin.ScalacCrossCompilingLayer$TweakedAnalyzer.rootContext$default$4(ScalacCrossCompilingLayer.scala:38)
	at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters.adapt(InteropCoerceTreeTransformer.scala:52)
	at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$CoercePhase$$anonfun$1.apply(InteropCoerceTreeTransformer.scala:42)
	at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$CoercePhase$$anonfun$1.apply(InteropCoerceTreeTransformer.scala:42)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
```